PROJECT_URL = "https://github.com/LibraryOfCongress/bagit-python"

STANDARD_BAG_INFO_HEADERS = [
    "Source-Organization",
    "Organization-Address",
    "Contact-Name",
    "Contact-Phone",
    "Contact-Email",
    "External-Description",
    "External-Identifier",
    "Bag-Size",
    "Bag-Group-Identifier",
    "Bag-Count",
    "Internal-Sender-Identifier",
    "Internal-Sender-Description",
    "BagIt-Profile-Identifier",
    # Bagging-Date is autogenerated
    # Payload-Oxum is autogenerated
]
HASH_BLOCK_SIZE = 512 * 1024
UNICODE_BYTE_ORDER_MARK = "\uFEFF"
DEFAULT_CHECKSUMS = ["sha256", "sha512"]
